project:
  type: website
  output-dir: _site
  # render:
  #   - photography/index.qmd
  # resources:
  #   - photography/js/

execute:
  freeze: auto

website:
  title: "msuatgunerli.github.io"
  site-url: "https://msuatgunerli.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about/index.qmd
        text: About Me
      - href: projects/index.qmd
        text: Projects
      - href: blog/index.qmd
        text: Blog
      - href: photography/index.qmd
        text: Photography
      - href: photography_beta/index.qmd
        text: Photography Beta

format:
  html:
    include-in-header:
      - text: |
          <script src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.2/masonry.pkgd.min.js"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/imagesloaded/5.0.0/imagesloaded.pkgd.min.js"></script>
    theme:
      - litera
      - brand
    css: styles.css
    toc: true