project:
  type: website
  output-dir: _site

execute:
  freeze: auto

website:
  title: "msuatgunerli.github.io"
  site-url: "https://msuatgunerli.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about/index.qmd
        text: About Me
      - href: projects/index.qmd
        text: Projects
      - href: blog/index.qmd
        text: Blog
      - href: photography/index.qmd
        text: Photography

format:
  html:
    theme:
      - litera
      - brand
    css: styles.css
    toc: true



